### PR TITLE
update controller module

### PR DESCRIPTION
**Pull request by drewmullen**
This PR provides:

- ami search by product code and allowing for version locking. you can still specify an AMI but i find it much easier to also allow for a search based on version + licensing type. ~**note** i have only been using BYOL. i attempted to determine which product code to use for licensed but **you should definitely confirm that i used the correct product code**~ using the hardcoded ami name i referenced the product_code in aws and used that. options are `byol` ami or `-PAID` license (what you had previously)
- count has been applied to conditionally created resources
- count logic is more straightforward using`==` instead of `!=`
- if keypair is created we now use `key_name_prefix` to allow for better use of tf workspaces
- added more variable defaults to make deploys easier
- added variable validation for variables that can fail during apply due to vendor specs. attempted to link to vendor docs where applicable
- allow user to define default admin password

*note* the `[0]` on some resources is required because we provided a `count` on the parent resource.

i have another update coming for gateway but i didnt want to overwhelm

### CODE REVIEW

**Comment by drewmullen** [comment]
instead of being lazy, i validated the license for `paid` since you had the name in there. i also included the command:

`aws ec2 describe-images --owners '679593333241' --region us-east-1 | less`
then just search for the product codes held in terraform

**Comment by drewmullen** [comment]
regarding product_codes, fyi i posted this on another appgate repo but i suspect it might not get any attention: https://github.com/appgate/appgate/issues/1

**Comment by drewmullen** [comment]
so i just noticed that it doesnt seem like `userdata` is actually being executed. 

i dont see a `/home/cz/seed.json` and i dont see anything in `/var/log/user-data*`. i found this in the instance logs:
`INFO [ActionsRunner] Running action InitCloudServiceAction(cloud_service=AwsCloudService(name='EC2', cloud_init_url='http://169.254.169.254', has_userdata=False, metadata_token=None, metadata_token_expiration_time=None))`

still investigating

**Comment by drewmullen** [comment]
on second thought, even though the userdata is stored in terraform as `sensitive`, its probably better to set the admin password in ssm and let the controller snag it through the instance_profile. i may not have time to do that today though but at the moment what i pushed is similar to what was there before (couldnt pass any, therefore default `admin`)

**Comment by danijeel** [comment]
Looks good to me, tried it out and worked as expected. try running `terraform fmt` [[1](https://www.terraform.io/docs/cli/commands/fmt.html)] on the controller module. 

About the AMI naming convention, we will come back with additional information about it at a later time.

**Comment by drewmullen** [comment]
to circle back on the password thing... i dont really love any of the solutions out of [terraform natively.](https://blog.gruntwork.io/a-comprehensive-guide-to-managing-secrets-in-your-terraform-code-1d586955ace1)
- store in state and encrypt your state file
- pre-write it to ssm then provide your root module with the param (fetch from ssm during userdata exec)

up to you on how you want to proceed but im fine with just leaving it as is and changing after initial boot

**Comment by danijeel** [comment]
> 
> 
> to circle back on the password thing... i dont really love any of the solutions out of [terraform natively.](https://blog.gruntwork.io/a-comprehensive-guide-to-managing-secrets-in-your-terraform-code-1d586955ace1)
> 
>     * store in state and encrypt your state file
> 
>     * pre-write it to ssm then provide your root module with the param (fetch from ssm during userdata exec)
> 
> 
> up to you on how you want to proceed but im fine with just leaving it as is and letting others change it themselves if theyre not comfortable having the pw in the state file
> 
> `fmt` complete


As I see it, this is just a reference project. it's up to the end user how they handle their state file and their sensitive variables. These modules are not intended to be used in production as is, but provide some boilerplate to get started with appgate in a terraform context.

thank you for your contribution, I will merge this PR! 👍🏻

**Pull request merged**
